import { Link } from "@tanstack/react-router";
import { Mail, Search, MessageSquare, Sparkles, Menu, X } from "lucide-react";
import { useState, type ReactNode } from "react";

const nav = [
  { to: "/", label: "Email Generator", icon: Mail },
  { to: "/research", label: "Research Assistant", icon: Search },
  { to: "/chat", label: "Workplace Chat", icon: MessageSquare },
] as const;

function NavLinks({ onNavigate }: { onNavigate?: () => void }) {
  return (
    <nav className="flex flex-col gap-1">
      {nav.map(({ to, label, icon: Icon }) => (
        <Link
          key={to}
          to={to}
          onClick={onNavigate}
          activeOptions={{ exact: to === "/" }}
          className="group flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-sidebar-foreground/70 transition-colors hover:bg-sidebar-accent hover:text-sidebar-foreground data-[status=active]:bg-sidebar-accent data-[status=active]:text-sidebar-foreground"
        >
          <Icon className="size-4 shrink-0" />
          {label}
        </Link>
      ))}
    </nav>
  );
}

function Brand() {
  return (
    <div className="flex items-center gap-2.5">
      <span className="flex size-9 items-center justify-center rounded-lg bg-primary text-primary-foreground">
        <Sparkles className="size-4.5" />
      </span>
      <span className="font-display text-base leading-tight font-semibold tracking-tight text-sidebar-foreground">
        Workplace AI
        <span className="block text-xs font-normal text-sidebar-foreground/55">Productivity Assistant</span>
      </span>
    </div>
  );
}

export function AppShell({
  title,
  description,
  children,
}: {
  title: string;
  description: string;
  children: ReactNode;
}) {
  const [open, setOpen] = useState(false);

  return (
    <div className="min-h-screen bg-background lg:grid lg:grid-cols-[17rem_1fr]">
      <aside className="hidden flex-col justify-between border-r border-sidebar-border bg-sidebar p-5 lg:sticky lg:top-0 lg:flex lg:h-screen">
        <div className="flex flex-col gap-8">
          <Brand />
          <NavLinks />
        </div>
        <p className="rounded-lg bg-sidebar-accent/60 p-3 text-xs leading-relaxed text-sidebar-foreground/60">
          Responsible AI: responses are generated by an AI model and may be inaccurate. Review and edit before
          sharing, and avoid entering confidential information.
        </p>
      </aside>

      <header className="sticky top-0 z-20 flex items-center justify-between border-b border-sidebar-border bg-sidebar px-4 py-3 lg:hidden">
        <Brand />
        <button
          aria-label={open ? "Close navigation" : "Open navigation"}
          onClick={() => setOpen((v) => !v)}
          className="rounded-md p-2 text-sidebar-foreground transition-colors hover:bg-sidebar-accent"
        >
          {open ? <X className="size-5" /> : <Menu className="size-5" />}
        </button>
      </header>
      {open && (
        <div className="sticky top-[57px] z-20 border-b border-sidebar-border bg-sidebar px-4 pb-4 lg:hidden">
          <NavLinks onNavigate={() => setOpen(false)} />
        </div>
      )}

      <main className="min-w-0 px-4 py-8 sm:px-8 lg:py-10">
        <div className="mx-auto w-full max-w-4xl">
          <div className="mb-8">
            <h1 className="font-display text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">
              {title}
            </h1>
            <p className="mt-2 max-w-2xl text-sm text-muted-foreground">{description}</p>
          </div>
          {children}
          <p className="mt-10 border-t border-border pt-4 text-xs text-muted-foreground lg:hidden">
            Responsible AI: responses are generated by an AI model and may be inaccurate. Review before sharing.
          </p>
        </div>
      </main>
    </div>
  );
}
